# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20170924_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='likes',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='retweets',
            new_name='retweet_count',
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 3, 7, 54, 283303, tzinfo=utc)),
        ),
    ]
