# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20170925_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='hashtag',
            field=models.CharField(default='#ShirleyTravels', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 18, 50, 42, 924599, tzinfo=utc)),
        ),
    ]
