# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20170925_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 14, 34, 38, 765985, tzinfo=utc)),
        ),
    ]
