# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-31 06:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20171115_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='emotion',
            field=models.CharField(default='happiness', max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 31, 6, 34, 19, 786772, tzinfo=utc)),
        ),
    ]
