# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_auto_20171231_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 2, 8, 12, 17, 904265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='hashtag',
            field=models.CharField(default='#katrinakaif', max_length=200),
        ),
    ]
